### ISSUE TITLE
add support for multiple versions of oc CLI

### ISSUE THREAD

**Issue by dudash** [dudash/openshift-wetty-client#10]

**Comment by dudash** [comment]
Also, add `odo`.
Keep a folder of all versions of these and symlink oc/odo to latest.
(Could copy from this gitrepo on Dockerfile build or wget from official)

**Comment by dmc5179** [comment]
Submitted https://github.com/dudash/openshift-wetty-client/pull/14

**Comment by dudash** [comment]
Thanks, I’ll take a look tonight
